#pragma once
/*
# ========================================================================================= #
# Defines
# ========================================================================================= #
*/

extern unsigned long long GObjects;
extern unsigned long long GNames;

/*
# ========================================================================================= #
# Structs
# ========================================================================================= #
*/
/*
class Rotator
{
public:
	int                                                Pitch;         
	int                                                Yaw;           
	int                                                Roll;          
};

class Vector3D
{
public:
	float x;
	float y;
	float z;
};

class Vector2D
{
public:
	float x;
	float y;
};

class Plane : Vector3D
{
public:
	float                                              W;                                                		// 0x000C (0x0004) [0x0000000000000000]              
};

class Vector4D
{
public:
	float                                              X;                                                		// 0x0000 (0x0004) [0x0000000000000000]              
	float                                              Y;                                                		// 0x0004 (0x0004) [0x0000000000000000]              
	float                                              Z;                                                		// 0x0008 (0x0004) [0x0000000000000000]              
	float                                              W;                                                		// 0x000C (0x0004) [0x0000000000000000]              
};
*/

/*
# ========================================================================================= #
# Includes
# ========================================================================================= #
*/

#include <Windows.h>
#include <set>
#include <string>
#include "SDK/UT4_Basic.hpp"

#include "SDK/UT4_CoreUObject_structs.hpp"
#include "SDK/UT4_CoreUObject_classes.hpp"
#include "SDK/UT4_CoreUObject_parameters.hpp"
#include "SDK/UT4_PacketHandler_structs.hpp"
#include "SDK/UT4_PacketHandler_classes.hpp"
#include "SDK/UT4_PacketHandler_parameters.hpp"
#include "SDK/UT4_InputCore_structs.hpp"
#include "SDK/UT4_InputCore_classes.hpp"
#include "SDK/UT4_InputCore_parameters.hpp"
#include "SDK/UT4_SlateCore_structs.hpp"
#include "SDK/UT4_SlateCore_classes.hpp"
#include "SDK/UT4_SlateCore_parameters.hpp"
#include "SDK/UT4_JsonUtilities_structs.hpp"
#include "SDK/UT4_JsonUtilities_classes.hpp"
#include "SDK/UT4_JsonUtilities_parameters.hpp"
#include "SDK/UT4_OnlineSubsystem_structs.hpp"
#include "SDK/UT4_OnlineSubsystem_classes.hpp"
#include "SDK/UT4_OnlineSubsystem_parameters.hpp"
#include "SDK/UT4_Slate_structs.hpp"
#include "SDK/UT4_Slate_classes.hpp"
#include "SDK/UT4_Slate_parameters.hpp"
#include "SDK/UT4_Engine_structs.hpp"
#include "SDK/UT4_Engine_classes.hpp"
#include "SDK/UT4_Engine_parameters.hpp"
#include "SDK/UT4_AnimGraphRuntime_structs.hpp"
#include "SDK/UT4_AnimGraphRuntime_classes.hpp"
#include "SDK/UT4_AnimGraphRuntime_parameters.hpp"
#include "SDK/UT4_GameplayTasks_structs.hpp"
#include "SDK/UT4_GameplayTasks_classes.hpp"
#include "SDK/UT4_GameplayTasks_parameters.hpp"
#include "SDK/UT4_SessionMessages_structs.hpp"
#include "SDK/UT4_SessionMessages_classes.hpp"
#include "SDK/UT4_SessionMessages_parameters.hpp"
#include "SDK/UT4_VectorVM_structs.hpp"
#include "SDK/UT4_VectorVM_classes.hpp"
#include "SDK/UT4_VectorVM_parameters.hpp"
#include "SDK/UT4_GameplayTags_structs.hpp"
#include "SDK/UT4_GameplayTags_classes.hpp"
#include "SDK/UT4_GameplayTags_parameters.hpp"
#include "SDK/UT4_MovieScene_structs.hpp"
#include "SDK/UT4_MovieScene_classes.hpp"
#include "SDK/UT4_MovieScene_parameters.hpp"
#include "SDK/UT4_MovieSceneTracks_structs.hpp"
#include "SDK/UT4_MovieSceneTracks_classes.hpp"
#include "SDK/UT4_MovieSceneTracks_parameters.hpp"
#include "SDK/UT4_AIModule_structs.hpp"
#include "SDK/UT4_AIModule_classes.hpp"
#include "SDK/UT4_AIModule_parameters.hpp"
#include "SDK/UT4_Party_structs.hpp"
#include "SDK/UT4_Party_classes.hpp"
#include "SDK/UT4_Party_parameters.hpp"
#include "SDK/UT4_OnlineSubsystemUtils_structs.hpp"
#include "SDK/UT4_OnlineSubsystemUtils_classes.hpp"
#include "SDK/UT4_OnlineSubsystemUtils_parameters.hpp"
#include "SDK/UT4_McpProfileSys_structs.hpp"
#include "SDK/UT4_McpProfileSys_classes.hpp"
#include "SDK/UT4_McpProfileSys_parameters.hpp"
#include "SDK/UT4_UTMcpProfile_structs.hpp"
#include "SDK/UT4_UTMcpProfile_classes.hpp"
#include "SDK/UT4_UTMcpProfile_parameters.hpp"
#include "SDK/UT4_GeometryCache_structs.hpp"
#include "SDK/UT4_GeometryCache_classes.hpp"
#include "SDK/UT4_GeometryCache_parameters.hpp"
#include "SDK/UT4_CinematicCamera_structs.hpp"
#include "SDK/UT4_CinematicCamera_classes.hpp"
#include "SDK/UT4_CinematicCamera_parameters.hpp"
#include "SDK/UT4_Niagara_structs.hpp"
#include "SDK/UT4_Niagara_classes.hpp"
#include "SDK/UT4_Niagara_parameters.hpp"
#include "SDK/UT4_Social_structs.hpp"
#include "SDK/UT4_Social_classes.hpp"
#include "SDK/UT4_Social_parameters.hpp"
#include "SDK/UT4_Foliage_structs.hpp"
#include "SDK/UT4_Foliage_classes.hpp"
#include "SDK/UT4_Foliage_parameters.hpp"
#include "SDK/UT4_UMG_structs.hpp"
#include "SDK/UT4_UMG_classes.hpp"
#include "SDK/UT4_UMG_parameters.hpp"
#include "SDK/UT4_UnrealTournament_structs.hpp"
#include "SDK/UT4_UnrealTournament_classes.hpp"
#include "SDK/UT4_UnrealTournament_parameters.hpp"
#include "SDK/UT4_LineUpVisualizationCharacter_structs.hpp"
#include "SDK/UT4_LineUpVisualizationCharacter_classes.hpp"
#include "SDK/UT4_LineUpVisualizationCharacter_parameters.hpp"
#include "SDK/UT4_BP_LightningDOT_structs.hpp"
#include "SDK/UT4_BP_LightningDOT_classes.hpp"
#include "SDK/UT4_BP_LightningDOT_parameters.hpp"
#include "SDK/UT4_Default_structs.hpp"
#include "SDK/UT4_Default_classes.hpp"
#include "SDK/UT4_Default_parameters.hpp"
#include "SDK/UT4_LineUpZone_structs.hpp"
#include "SDK/UT4_LineUpZone_classes.hpp"
#include "SDK/UT4_LineUpZone_parameters.hpp"
#include "SDK/UT4_Taunt_Bow_structs.hpp"
#include "SDK/UT4_Taunt_Bow_classes.hpp"
#include "SDK/UT4_Taunt_Bow_parameters.hpp"
#include "SDK/UT4_Taunt_Boom_structs.hpp"
#include "SDK/UT4_Taunt_Boom_classes.hpp"
#include "SDK/UT4_Taunt_Boom_parameters.hpp"
#include "SDK/UT4_GroupTaunt_Bow_structs.hpp"
#include "SDK/UT4_GroupTaunt_Bow_classes.hpp"
#include "SDK/UT4_GroupTaunt_Bow_parameters.hpp"
#include "SDK/UT4_UT4_Base_AnimBP_structs.hpp"
#include "SDK/UT4_UT4_Base_AnimBP_classes.hpp"
#include "SDK/UT4_UT4_Base_AnimBP_parameters.hpp"
#include "SDK/UT4_BP_LeaderBeret_structs.hpp"
#include "SDK/UT4_BP_LeaderBeret_classes.hpp"
#include "SDK/UT4_BP_LeaderBeret_parameters.hpp"
#include "SDK/UT4_PlayerPreviewEnvironment_structs.hpp"
#include "SDK/UT4_PlayerPreviewEnvironment_classes.hpp"
#include "SDK/UT4_PlayerPreviewEnvironment_parameters.hpp"
#include "SDK/UT4_BP_Skaarj_Dreads_structs.hpp"
#include "SDK/UT4_BP_Skaarj_Dreads_classes.hpp"
#include "SDK/UT4_BP_Skaarj_Dreads_parameters.hpp"
#include "SDK/UT4_ChainLightningMessage_structs.hpp"
#include "SDK/UT4_ChainLightningMessage_classes.hpp"
#include "SDK/UT4_ChainLightningMessage_parameters.hpp"
#include "SDK/UT4_UTDMG_LightningBeam_structs.hpp"
#include "SDK/UT4_UTDMG_LightningBeam_classes.hpp"
#include "SDK/UT4_UTDMG_LightningBeam_parameters.hpp"
#include "SDK/UT4_UTDMG_LightningBeamChain_structs.hpp"
#include "SDK/UT4_UTDMG_LightningBeamChain_classes.hpp"
#include "SDK/UT4_UTDMG_LightningBeamChain_parameters.hpp"
#include "SDK/UT4_BP_UTDmg_LightningHeadshot_structs.hpp"
#include "SDK/UT4_BP_UTDmg_LightningHeadshot_classes.hpp"
#include "SDK/UT4_BP_UTDmg_LightningHeadshot_parameters.hpp"
#include "SDK/UT4_Lightning_Gun_1p_animBP_structs.hpp"
#include "SDK/UT4_Lightning_Gun_1p_animBP_classes.hpp"
#include "SDK/UT4_Lightning_Gun_1p_animBP_parameters.hpp"
#include "SDK/UT4_Sniper_Rifle_1p_animBP_structs.hpp"
#include "SDK/UT4_Sniper_Rifle_1p_animBP_classes.hpp"
#include "SDK/UT4_Sniper_Rifle_1p_animBP_parameters.hpp"
#include "SDK/UT4_LightningHitEffect_structs.hpp"
#include "SDK/UT4_LightningHitEffect_classes.hpp"
#include "SDK/UT4_LightningHitEffect_parameters.hpp"
#include "SDK/UT4_LightningHitEffect_Proj_structs.hpp"
#include "SDK/UT4_LightningHitEffect_Proj_classes.hpp"
#include "SDK/UT4_LightningHitEffect_Proj_parameters.hpp"
#include "SDK/UT4_UTDMG_LightningProj_structs.hpp"
#include "SDK/UT4_UTDMG_LightningProj_classes.hpp"
#include "SDK/UT4_UTDMG_LightningProj_parameters.hpp"
#include "SDK/UT4_BP_LightningRifle_Proj_structs.hpp"
#include "SDK/UT4_BP_LightningRifle_Proj_classes.hpp"
#include "SDK/UT4_BP_LightningRifle_Proj_parameters.hpp"
#include "SDK/UT4_BP_LightningRifle_Attach_structs.hpp"
#include "SDK/UT4_BP_LightningRifle_Attach_classes.hpp"
#include "SDK/UT4_BP_LightningRifle_Attach_parameters.hpp"
#include "SDK/UT4_BP_LightningRifle_structs.hpp"
#include "SDK/UT4_BP_LightningRifle_classes.hpp"
#include "SDK/UT4_BP_LightningRifle_parameters.hpp"
#include "SDK/UT4_UTDmg_Sniper_structs.hpp"
#include "SDK/UT4_UTDmg_Sniper_classes.hpp"
#include "SDK/UT4_UTDmg_Sniper_parameters.hpp"
#include "SDK/UT4_HeadShotMessage_structs.hpp"
#include "SDK/UT4_HeadShotMessage_classes.hpp"
#include "SDK/UT4_HeadShotMessage_parameters.hpp"
#include "SDK/UT4_BP_UTDmg_SniperHeadshot_structs.hpp"
#include "SDK/UT4_BP_UTDmg_SniperHeadshot_classes.hpp"
#include "SDK/UT4_BP_UTDmg_SniperHeadshot_parameters.hpp"
#include "SDK/UT4_BP_Sniper_Attach_structs.hpp"
#include "SDK/UT4_BP_Sniper_Attach_classes.hpp"
#include "SDK/UT4_BP_Sniper_Attach_parameters.hpp"
#include "SDK/UT4_SniperBulletImpact_structs.hpp"
#include "SDK/UT4_SniperBulletImpact_classes.hpp"
#include "SDK/UT4_SniperBulletImpact_parameters.hpp"
#include "SDK/UT4_BP_Sniper_structs.hpp"
#include "SDK/UT4_BP_Sniper_classes.hpp"
#include "SDK/UT4_BP_Sniper_parameters.hpp"
#include "SDK/UT4_UTDmg_ShockCore_structs.hpp"
#include "SDK/UT4_UTDmg_ShockCore_classes.hpp"
#include "SDK/UT4_UTDmg_ShockCore_parameters.hpp"
#include "SDK/UT4_UTDmg_ShockCombo_structs.hpp"
#include "SDK/UT4_UTDmg_ShockCombo_classes.hpp"
#include "SDK/UT4_UTDmg_ShockCombo_parameters.hpp"
#include "SDK/UT4_UTDmg_ShockBeam_structs.hpp"
#include "SDK/UT4_UTDmg_ShockBeam_classes.hpp"
#include "SDK/UT4_UTDmg_ShockBeam_parameters.hpp"
#include "SDK/UT4_ShockBallExplosion_structs.hpp"
#include "SDK/UT4_ShockBallExplosion_classes.hpp"
#include "SDK/UT4_ShockBallExplosion_parameters.hpp"
#include "SDK/UT4_ComboExplosion_structs.hpp"
#include "SDK/UT4_ComboExplosion_classes.hpp"
#include "SDK/UT4_ComboExplosion_parameters.hpp"
#include "SDK/UT4_BP_Flowing_Water_structs.hpp"
#include "SDK/UT4_BP_Flowing_Water_classes.hpp"
#include "SDK/UT4_BP_Flowing_Water_parameters.hpp"
#include "SDK/UT4_SniperAnimBP_structs.hpp"
#include "SDK/UT4_SniperAnimBP_classes.hpp"
#include "SDK/UT4_SniperAnimBP_parameters.hpp"
#include "SDK/UT4_ComboVortex_structs.hpp"
#include "SDK/UT4_ComboVortex_classes.hpp"
#include "SDK/UT4_ComboVortex_parameters.hpp"
#include "SDK/UT4_AwesomComboReward_structs.hpp"
#include "SDK/UT4_AwesomComboReward_classes.hpp"
#include "SDK/UT4_AwesomComboReward_parameters.hpp"
#include "SDK/UT4_PancakeReward_structs.hpp"
#include "SDK/UT4_PancakeReward_classes.hpp"
#include "SDK/UT4_PancakeReward_parameters.hpp"
#include "SDK/UT4_WeaponIDs_structs.hpp"
#include "SDK/UT4_WeaponIDs_classes.hpp"
#include "SDK/UT4_WeaponIDs_parameters.hpp"
#include "SDK/UT4_Dmg_FallingCrush_structs.hpp"
#include "SDK/UT4_Dmg_FallingCrush_classes.hpp"
#include "SDK/UT4_Dmg_FallingCrush_parameters.hpp"
#include "SDK/UT4_Taunt_Clawpose_structs.hpp"
#include "SDK/UT4_Taunt_Clawpose_classes.hpp"
#include "SDK/UT4_Taunt_Clawpose_parameters.hpp"
#include "SDK/UT4_BP_RallyEnd_blue_structs.hpp"
#include "SDK/UT4_BP_RallyEnd_blue_classes.hpp"
#include "SDK/UT4_BP_RallyEnd_blue_parameters.hpp"
#include "SDK/UT4_BP_RallyEnd_Red_structs.hpp"
#include "SDK/UT4_BP_RallyEnd_Red_classes.hpp"
#include "SDK/UT4_BP_RallyEnd_Red_parameters.hpp"
#include "SDK/UT4_BP_RallyDest_structs.hpp"
#include "SDK/UT4_BP_RallyDest_classes.hpp"
#include "SDK/UT4_BP_RallyDest_parameters.hpp"
#include "SDK/UT4_Base_3p_AnimBP_structs.hpp"
#include "SDK/UT4_Base_3p_AnimBP_classes.hpp"
#include "SDK/UT4_Base_3p_AnimBP_parameters.hpp"
#include "SDK/UT4_Grenade_Launcher_1p_animBP_structs.hpp"
#include "SDK/UT4_Grenade_Launcher_1p_animBP_classes.hpp"
#include "SDK/UT4_Grenade_Launcher_1p_animBP_parameters.hpp"
#include "SDK/UT4_BP_RallyDest_Blue_structs.hpp"
#include "SDK/UT4_BP_RallyDest_Blue_classes.hpp"
#include "SDK/UT4_BP_RallyDest_Blue_parameters.hpp"
#include "SDK/UT4_BioRifle_AnimBP_structs.hpp"
#include "SDK/UT4_BioRifle_AnimBP_classes.hpp"
#include "SDK/UT4_BioRifle_AnimBP_parameters.hpp"
#include "SDK/UT4_BP_RallyDest_Red_structs.hpp"
#include "SDK/UT4_BP_RallyDest_Red_classes.hpp"
#include "SDK/UT4_BP_RallyDest_Red_parameters.hpp"
#include "SDK/UT4_BlueTeleportEffect_structs.hpp"
#include "SDK/UT4_BlueTeleportEffect_classes.hpp"
#include "SDK/UT4_BlueTeleportEffect_parameters.hpp"
#include "SDK/UT4_base_1p_AnimBP_structs.hpp"
#include "SDK/UT4_base_1p_AnimBP_classes.hpp"
#include "SDK/UT4_base_1p_AnimBP_parameters.hpp"
#include "SDK/UT4_Shock_Rifle_1p_animBP_structs.hpp"
#include "SDK/UT4_Shock_Rifle_1p_animBP_classes.hpp"
#include "SDK/UT4_Shock_Rifle_1p_animBP_parameters.hpp"
#include "SDK/UT4_RedTeleportEffect_structs.hpp"
#include "SDK/UT4_RedTeleportEffect_classes.hpp"
#include "SDK/UT4_RedTeleportEffect_parameters.hpp"
#include "SDK/UT4_UTDmg_GrenadeLauncher_Sticky_structs.hpp"
#include "SDK/UT4_UTDmg_GrenadeLauncher_Sticky_classes.hpp"
#include "SDK/UT4_UTDmg_GrenadeLauncher_Sticky_parameters.hpp"
#include "SDK/UT4_Shock_AnimBP_1p_structs.hpp"
#include "SDK/UT4_Shock_AnimBP_1p_classes.hpp"
#include "SDK/UT4_Shock_AnimBP_1p_parameters.hpp"
#include "SDK/UT4_Rocket_Launcher_1p_animBP_structs.hpp"
#include "SDK/UT4_Rocket_Launcher_1p_animBP_classes.hpp"
#include "SDK/UT4_Rocket_Launcher_1p_animBP_parameters.hpp"
#include "SDK/UT4_GrenadeExplode_Sticky_structs.hpp"
#include "SDK/UT4_GrenadeExplode_Sticky_classes.hpp"
#include "SDK/UT4_GrenadeExplode_Sticky_parameters.hpp"
#include "SDK/UT4_BP_Grenade_Sticky_structs.hpp"
#include "SDK/UT4_BP_Grenade_Sticky_classes.hpp"
#include "SDK/UT4_BP_Grenade_Sticky_parameters.hpp"
#include "SDK/UT4_UTDmg_GrenadeLauncher_structs.hpp"
#include "SDK/UT4_UTDmg_GrenadeLauncher_classes.hpp"
#include "SDK/UT4_UTDmg_GrenadeLauncher_parameters.hpp"
#include "SDK/UT4_GrenadeExplodeBig_structs.hpp"
#include "SDK/UT4_GrenadeExplodeBig_classes.hpp"
#include "SDK/UT4_GrenadeExplodeBig_parameters.hpp"
#include "SDK/UT4_BP_Grenade_structs.hpp"
#include "SDK/UT4_BP_Grenade_classes.hpp"
#include "SDK/UT4_BP_Grenade_parameters.hpp"
#include "SDK/UT4_GrenadeDetonateIndicator_structs.hpp"
#include "SDK/UT4_GrenadeDetonateIndicator_classes.hpp"
#include "SDK/UT4_GrenadeDetonateIndicator_parameters.hpp"
#include "SDK/UT4_BP_GrenadeLauncher_Attach_structs.hpp"
#include "SDK/UT4_BP_GrenadeLauncher_Attach_classes.hpp"
#include "SDK/UT4_BP_GrenadeLauncher_Attach_parameters.hpp"
#include "SDK/UT4_BP_GrenadeLauncher_structs.hpp"
#include "SDK/UT4_BP_GrenadeLauncher_classes.hpp"
#include "SDK/UT4_BP_GrenadeLauncher_parameters.hpp"
#include "SDK/UT4_BaseUTCharacter_structs.hpp"
#include "SDK/UT4_BaseUTCharacter_classes.hpp"
#include "SDK/UT4_BaseUTCharacter_parameters.hpp"
#include "SDK/UT4_ShockBall_structs.hpp"
#include "SDK/UT4_ShockBall_classes.hpp"
#include "SDK/UT4_ShockBall_parameters.hpp"
#include "SDK/UT4_SK_WP_RocketLauncher_3P_AnimBP_structs.hpp"
#include "SDK/UT4_SK_WP_RocketLauncher_3P_AnimBP_classes.hpp"
#include "SDK/UT4_SK_WP_RocketLauncher_3P_AnimBP_parameters.hpp"
#include "SDK/UT4_ShockAttachment_structs.hpp"
#include "SDK/UT4_ShockAttachment_classes.hpp"
#include "SDK/UT4_ShockAttachment_parameters.hpp"
#include "SDK/UT4_ShockBeamImpact_structs.hpp"
#include "SDK/UT4_ShockBeamImpact_classes.hpp"
#include "SDK/UT4_ShockBeamImpact_parameters.hpp"
#include "SDK/UT4_ShockRifle_structs.hpp"
#include "SDK/UT4_ShockRifle_classes.hpp"
#include "SDK/UT4_ShockRifle_parameters.hpp"
#include "SDK/UT4_BP_Rocket_Attachment_structs.hpp"
#include "SDK/UT4_BP_Rocket_Attachment_classes.hpp"
#include "SDK/UT4_BP_Rocket_Attachment_parameters.hpp"
#include "SDK/UT4_BP_Rocket_Projectile_structs.hpp"
#include "SDK/UT4_BP_Rocket_Projectile_classes.hpp"
#include "SDK/UT4_BP_Rocket_Projectile_parameters.hpp"
#include "SDK/UT4_FX_GrenadeExplosion_structs.hpp"
#include "SDK/UT4_FX_GrenadeExplosion_classes.hpp"
#include "SDK/UT4_FX_GrenadeExplosion_parameters.hpp"
#include "SDK/UT4_Rocket_AnimBP_structs.hpp"
#include "SDK/UT4_Rocket_AnimBP_classes.hpp"
#include "SDK/UT4_Rocket_AnimBP_parameters.hpp"
#include "SDK/UT4_MiniGun_1p_AnimBP_structs.hpp"
#include "SDK/UT4_MiniGun_1p_AnimBP_classes.hpp"
#include "SDK/UT4_MiniGun_1p_AnimBP_parameters.hpp"
#include "SDK/UT4_BP_RocketGrenade_structs.hpp"
#include "SDK/UT4_BP_RocketGrenade_classes.hpp"
#include "SDK/UT4_BP_RocketGrenade_parameters.hpp"
#include "SDK/UT4_UTDMG_Rocket_structs.hpp"
#include "SDK/UT4_UTDMG_Rocket_classes.hpp"
#include "SDK/UT4_UTDMG_Rocket_parameters.hpp"
#include "SDK/UT4_FX_RocketExplosion_structs.hpp"
#include "SDK/UT4_FX_RocketExplosion_classes.hpp"
#include "SDK/UT4_FX_RocketExplosion_parameters.hpp"
#include "SDK/UT4_AirRocketReward_structs.hpp"
#include "SDK/UT4_AirRocketReward_classes.hpp"
#include "SDK/UT4_AirRocketReward_parameters.hpp"
#include "SDK/UT4_BP_RocketSeeking_structs.hpp"
#include "SDK/UT4_BP_RocketSeeking_classes.hpp"
#include "SDK/UT4_BP_RocketSeeking_parameters.hpp"
#include "SDK/UT4_BP_LinkAlt_3P_structs.hpp"
#include "SDK/UT4_BP_LinkAlt_3P_classes.hpp"
#include "SDK/UT4_BP_LinkAlt_3P_parameters.hpp"
#include "SDK/UT4_BP_RocketLauncher_structs.hpp"
#include "SDK/UT4_BP_RocketLauncher_classes.hpp"
#include "SDK/UT4_BP_RocketLauncher_parameters.hpp"
#include "SDK/UT4_UTDMG_Minigun_Primary_structs.hpp"
#include "SDK/UT4_UTDMG_Minigun_Primary_classes.hpp"
#include "SDK/UT4_UTDMG_Minigun_Primary_parameters.hpp"
#include "SDK/UT4_StingerImpact_structs.hpp"
#include "SDK/UT4_StingerImpact_classes.hpp"
#include "SDK/UT4_StingerImpact_parameters.hpp"
#include "SDK/UT4_SK_WP_Stinger_1P_Skeleton_AnimBlueprint_structs.hpp"
#include "SDK/UT4_SK_WP_Stinger_1P_Skeleton_AnimBlueprint_classes.hpp"
#include "SDK/UT4_SK_WP_Stinger_1P_Skeleton_AnimBlueprint_parameters.hpp"
#include "SDK/UT4_LinkGun_1p_animBP_structs.hpp"
#include "SDK/UT4_LinkGun_1p_animBP_classes.hpp"
#include "SDK/UT4_LinkGun_1p_animBP_parameters.hpp"
#include "SDK/UT4_BP_LinkAlt_1P_structs.hpp"
#include "SDK/UT4_BP_LinkAlt_1P_classes.hpp"
#include "SDK/UT4_BP_LinkAlt_1P_parameters.hpp"
#include "SDK/UT4_UTDMG_Minigun_Alt_structs.hpp"
#include "SDK/UT4_UTDMG_Minigun_Alt_classes.hpp"
#include "SDK/UT4_UTDMG_Minigun_Alt_parameters.hpp"
#include "SDK/UT4_MinigunProjImpactEffectRadial_structs.hpp"
#include "SDK/UT4_MinigunProjImpactEffectRadial_classes.hpp"
#include "SDK/UT4_MinigunProjImpactEffectRadial_parameters.hpp"
#include "SDK/UT4_Minigun_ProjectileNew_structs.hpp"
#include "SDK/UT4_Minigun_ProjectileNew_classes.hpp"
#include "SDK/UT4_Minigun_ProjectileNew_parameters.hpp"
#include "SDK/UT4_Minigun_Attachment_structs.hpp"
#include "SDK/UT4_Minigun_Attachment_classes.hpp"
#include "SDK/UT4_Minigun_Attachment_parameters.hpp"
#include "SDK/UT4_BP_Minigun_structs.hpp"
#include "SDK/UT4_BP_Minigun_classes.hpp"
#include "SDK/UT4_BP_Minigun_parameters.hpp"
#include "SDK/UT4_YoinkMessage_structs.hpp"
#include "SDK/UT4_YoinkMessage_classes.hpp"
#include "SDK/UT4_YoinkMessage_parameters.hpp"
#include "SDK/UT4_LinkGun_Anim_BP_structs.hpp"
#include "SDK/UT4_LinkGun_Anim_BP_classes.hpp"
#include "SDK/UT4_LinkGun_Anim_BP_parameters.hpp"
#include "SDK/UT4_Impact_Hammer_1p_AnimBP_structs.hpp"
#include "SDK/UT4_Impact_Hammer_1p_AnimBP_classes.hpp"
#include "SDK/UT4_Impact_Hammer_1p_AnimBP_parameters.hpp"
#include "SDK/UT4_UTDMG_Link_AltPulse_structs.hpp"
#include "SDK/UT4_UTDMG_Link_AltPulse_classes.hpp"
#include "SDK/UT4_UTDMG_Link_AltPulse_parameters.hpp"
#include "SDK/UT4_UTDMG_Link_Alt_structs.hpp"
#include "SDK/UT4_UTDMG_Link_Alt_classes.hpp"
#include "SDK/UT4_UTDMG_Link_Alt_parameters.hpp"
#include "SDK/UT4_LinkBeamImpactEffect_structs.hpp"
#include "SDK/UT4_LinkBeamImpactEffect_classes.hpp"
#include "SDK/UT4_LinkBeamImpactEffect_parameters.hpp"
#include "SDK/UT4_BP_LinkGun_Attach_structs.hpp"
#include "SDK/UT4_BP_LinkGun_Attach_classes.hpp"
#include "SDK/UT4_BP_LinkGun_Attach_parameters.hpp"
#include "SDK/UT4_UTDMG_Link_Primary_structs.hpp"
#include "SDK/UT4_UTDMG_Link_Primary_classes.hpp"
#include "SDK/UT4_UTDMG_Link_Primary_parameters.hpp"
#include "SDK/UT4_LinkPrimaryHitEffect_structs.hpp"
#include "SDK/UT4_LinkPrimaryHitEffect_classes.hpp"
#include "SDK/UT4_LinkPrimaryHitEffect_parameters.hpp"
#include "SDK/UT4_BP_Link_Proj_structs.hpp"
#include "SDK/UT4_BP_Link_Proj_classes.hpp"
#include "SDK/UT4_BP_Link_Proj_parameters.hpp"
#include "SDK/UT4_BP_LinkGun_structs.hpp"
#include "SDK/UT4_BP_LinkGun_classes.hpp"
#include "SDK/UT4_BP_LinkGun_parameters.hpp"
#include "SDK/UT4_ImpactHammerReward_structs.hpp"
#include "SDK/UT4_ImpactHammerReward_classes.hpp"
#include "SDK/UT4_ImpactHammerReward_parameters.hpp"
#include "SDK/UT4_UTDmg_ImpactHammer_structs.hpp"
#include "SDK/UT4_UTDmg_ImpactHammer_classes.hpp"
#include "SDK/UT4_UTDmg_ImpactHammer_parameters.hpp"
#include "SDK/UT4_SK_WP_Impact_1P_AnimBlueprint_structs.hpp"
#include "SDK/UT4_SK_WP_Impact_1P_AnimBlueprint_classes.hpp"
#include "SDK/UT4_SK_WP_Impact_1P_AnimBlueprint_parameters.hpp"
#include "SDK/UT4_Flak_Cannon_1p_animBP_structs.hpp"
#include "SDK/UT4_Flak_Cannon_1p_animBP_classes.hpp"
#include "SDK/UT4_Flak_Cannon_1p_animBP_parameters.hpp"
#include "SDK/UT4_UTDmg_ImpactHammerBlock_structs.hpp"
#include "SDK/UT4_UTDmg_ImpactHammerBlock_classes.hpp"
#include "SDK/UT4_UTDmg_ImpactHammerBlock_parameters.hpp"
#include "SDK/UT4_ImpactHammerShieldProj_structs.hpp"
#include "SDK/UT4_ImpactHammerShieldProj_classes.hpp"
#include "SDK/UT4_ImpactHammerShieldProj_parameters.hpp"
#include "SDK/UT4_BP_ImpactHammer_Attach_structs.hpp"
#include "SDK/UT4_BP_ImpactHammer_Attach_classes.hpp"
#include "SDK/UT4_BP_ImpactHammer_Attach_parameters.hpp"
#include "SDK/UT4_BP_ImpactHammer_structs.hpp"
#include "SDK/UT4_BP_ImpactHammer_classes.hpp"
#include "SDK/UT4_BP_ImpactHammer_parameters.hpp"
#include "SDK/UT4_Rejoin_structs.hpp"
#include "SDK/UT4_Rejoin_classes.hpp"
#include "SDK/UT4_Rejoin_parameters.hpp"
#include "SDK/UT4_Hotfix_structs.hpp"
#include "SDK/UT4_Hotfix_classes.hpp"
#include "SDK/UT4_Hotfix_parameters.hpp"
#include "SDK/UT4_Vivox_structs.hpp"
#include "SDK/UT4_Vivox_classes.hpp"
#include "SDK/UT4_Vivox_parameters.hpp"
#include "SDK/UT4_UTDmg_FlakShell_structs.hpp"
#include "SDK/UT4_UTDmg_FlakShell_classes.hpp"
#include "SDK/UT4_UTDmg_FlakShell_parameters.hpp"
#include "SDK/UT4_Flak_Shard_structs.hpp"
#include "SDK/UT4_Flak_Shard_classes.hpp"
#include "SDK/UT4_Flak_Shard_parameters.hpp"
#include "SDK/UT4_Flak_AnimBP_structs.hpp"
#include "SDK/UT4_Flak_AnimBP_classes.hpp"
#include "SDK/UT4_Flak_AnimBP_parameters.hpp"
#include "SDK/UT4_Enforcer_1p_animBP_structs.hpp"
#include "SDK/UT4_Enforcer_1p_animBP_classes.hpp"
#include "SDK/UT4_Enforcer_1p_animBP_parameters.hpp"
#include "SDK/UT4_FlakShellExplosion_structs.hpp"
#include "SDK/UT4_FlakShellExplosion_classes.hpp"
#include "SDK/UT4_FlakShellExplosion_parameters.hpp"
#include "SDK/UT4_UT-Entry_structs.hpp"
#include "SDK/UT4_UT-Entry_classes.hpp"
#include "SDK/UT4_UT-Entry_parameters.hpp"
#include "SDK/UT4_Flak_Shell_structs.hpp"
#include "SDK/UT4_Flak_Shell_classes.hpp"
#include "SDK/UT4_Flak_Shell_parameters.hpp"
#include "SDK/UT4_CloseFlakRewardMessage_structs.hpp"
#include "SDK/UT4_CloseFlakRewardMessage_classes.hpp"
#include "SDK/UT4_CloseFlakRewardMessage_parameters.hpp"
#include "SDK/UT4_CorsairRGB_structs.hpp"
#include "SDK/UT4_CorsairRGB_classes.hpp"
#include "SDK/UT4_CorsairRGB_parameters.hpp"
#include "SDK/UT4_RazerChroma_structs.hpp"
#include "SDK/UT4_RazerChroma_classes.hpp"
#include "SDK/UT4_RazerChroma_parameters.hpp"
#include "SDK/UT4_WebMRecord_structs.hpp"
#include "SDK/UT4_WebMRecord_classes.hpp"
#include "SDK/UT4_WebMRecord_parameters.hpp"
#include "SDK/UT4_HTML5Networking_structs.hpp"
#include "SDK/UT4_HTML5Networking_classes.hpp"
#include "SDK/UT4_HTML5Networking_parameters.hpp"
#include "SDK/UT4_MobilePatchingUtils_structs.hpp"
#include "SDK/UT4_MobilePatchingUtils_classes.hpp"
#include "SDK/UT4_MobilePatchingUtils_parameters.hpp"
#include "SDK/UT4_CableComponent_structs.hpp"
#include "SDK/UT4_CableComponent_classes.hpp"
#include "SDK/UT4_CableComponent_parameters.hpp"
#include "SDK/UT4_ArchVisCharacter_structs.hpp"
#include "SDK/UT4_ArchVisCharacter_classes.hpp"
#include "SDK/UT4_ArchVisCharacter_parameters.hpp"
#include "SDK/UT4_Flak_Shard_Main_structs.hpp"
#include "SDK/UT4_Flak_Shard_Main_classes.hpp"
#include "SDK/UT4_Flak_Shard_Main_parameters.hpp"
#include "SDK/UT4_CustomMeshComponent_structs.hpp"
#include "SDK/UT4_CustomMeshComponent_classes.hpp"
#include "SDK/UT4_CustomMeshComponent_parameters.hpp"
#include "SDK/UT4_ProceduralMeshComponent_structs.hpp"
#include "SDK/UT4_ProceduralMeshComponent_classes.hpp"
#include "SDK/UT4_ProceduralMeshComponent_parameters.hpp"
#include "SDK/UT4_GameSubCatalog_structs.hpp"
#include "SDK/UT4_GameSubCatalog_classes.hpp"
#include "SDK/UT4_GameSubCatalog_parameters.hpp"
#include "SDK/UT4_UTDmg_FlakShard_structs.hpp"
#include "SDK/UT4_UTDmg_FlakShard_classes.hpp"
#include "SDK/UT4_UTDmg_FlakShard_parameters.hpp"
#include "SDK/UT4_FlakShell_Shard_structs.hpp"
#include "SDK/UT4_FlakShell_Shard_classes.hpp"
#include "SDK/UT4_FlakShell_Shard_parameters.hpp"
#include "SDK/UT4_BP_Flak_Attach_structs.hpp"
#include "SDK/UT4_BP_Flak_Attach_classes.hpp"
#include "SDK/UT4_BP_Flak_Attach_parameters.hpp"
#include "SDK/UT4_BP_FlakCannon_structs.hpp"
#include "SDK/UT4_BP_FlakCannon_classes.hpp"
#include "SDK/UT4_BP_FlakCannon_parameters.hpp"
#include "SDK/UT4_UTDMG_Enforcer_structs.hpp"
#include "SDK/UT4_UTDMG_Enforcer_classes.hpp"
#include "SDK/UT4_UTDMG_Enforcer_parameters.hpp"
#include "SDK/UT4_Enforcer_Attach_structs.hpp"
#include "SDK/UT4_Enforcer_Attach_classes.hpp"
#include "SDK/UT4_Enforcer_Attach_parameters.hpp"
#include "SDK/UT4_Dual_Enforcer_Attach_structs.hpp"
#include "SDK/UT4_Dual_Enforcer_Attach_classes.hpp"
#include "SDK/UT4_Dual_Enforcer_Attach_parameters.hpp"
#include "SDK/UT4_EnforcerImpactEffect_structs.hpp"
#include "SDK/UT4_EnforcerImpactEffect_classes.hpp"
#include "SDK/UT4_EnforcerImpactEffect_parameters.hpp"
#include "SDK/UT4_GameSpeedMutatorMenu_structs.hpp"
#include "SDK/UT4_GameSpeedMutatorMenu_classes.hpp"
#include "SDK/UT4_GameSpeedMutatorMenu_parameters.hpp"
#include "SDK/UT4_RewardAnnouncerMale_structs.hpp"
#include "SDK/UT4_RewardAnnouncerMale_classes.hpp"
#include "SDK/UT4_RewardAnnouncerMale_parameters.hpp"
#include "SDK/UT4_Lobby_structs.hpp"
#include "SDK/UT4_Lobby_classes.hpp"
#include "SDK/UT4_Lobby_parameters.hpp"
#include "SDK/UT4_Enforcer_structs.hpp"
#include "SDK/UT4_Enforcer_classes.hpp"
#include "SDK/UT4_Enforcer_parameters.hpp"
#include "SDK/UT4_SampleGameMode_structs.hpp"
#include "SDK/UT4_SampleGameMode_classes.hpp"
#include "SDK/UT4_SampleGameMode_parameters.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_Base_structs.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_Base_classes.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_Base_parameters.hpp"
#include "SDK/UT4_TutTrainingInfoBox_structs.hpp"
#include "SDK/UT4_TutTrainingInfoBox_classes.hpp"
#include "SDK/UT4_TutTrainingInfoBox_parameters.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_Replacement_structs.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_Replacement_classes.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_Replacement_parameters.hpp"
#include "SDK/UT4_WebBrowser_structs.hpp"
#include "SDK/UT4_WebBrowser_classes.hpp"
#include "SDK/UT4_WebBrowser_parameters.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_structs.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_classes.hpp"
#include "SDK/UT4_Mutator_WeaponReplacementUI_parameters.hpp"
#include "SDK/UT4_ArenaMutatorMenu_structs.hpp"
#include "SDK/UT4_ArenaMutatorMenu_classes.hpp"
#include "SDK/UT4_ArenaMutatorMenu_parameters.hpp"
#include "SDK/UT4_TutMainMenuWidget_structs.hpp"
#include "SDK/UT4_TutMainMenuWidget_classes.hpp"
#include "SDK/UT4_TutMainMenuWidget_parameters.hpp"
#include "SDK/UT4_BP_FlagSplineCreator_structs.hpp"
#include "SDK/UT4_BP_FlagSplineCreator_classes.hpp"
#include "SDK/UT4_BP_FlagSplineCreator_parameters.hpp"
#include "SDK/UT4_TextStyle-Base_structs.hpp"
#include "SDK/UT4_TextStyle-Base_classes.hpp"
#include "SDK/UT4_TextStyle-Base_parameters.hpp"
#include "SDK/UT4_TextStyle-Body_structs.hpp"
#include "SDK/UT4_TextStyle-Body_classes.hpp"
#include "SDK/UT4_TextStyle-Body_parameters.hpp"
#include "SDK/UT4_MonsterHealthDropMedium_structs.hpp"
#include "SDK/UT4_MonsterHealthDropMedium_classes.hpp"
#include "SDK/UT4_MonsterHealthDropMedium_parameters.hpp"
#include "SDK/UT4_BaseCharacterBloodExplosion_structs.hpp"
#include "SDK/UT4_BaseCharacterBloodExplosion_classes.hpp"
#include "SDK/UT4_BaseCharacterBloodExplosion_parameters.hpp"
#include "SDK/UT4_HumanMaleBase_structs.hpp"
#include "SDK/UT4_HumanMaleBase_classes.hpp"
#include "SDK/UT4_HumanMaleBase_parameters.hpp"
#include "SDK/UT4_LightPropagationVolumeRuntime_structs.hpp"
#include "SDK/UT4_LightPropagationVolumeRuntime_classes.hpp"
#include "SDK/UT4_LightPropagationVolumeRuntime_parameters.hpp"
#include "SDK/UT4_TcpMessaging_structs.hpp"
#include "SDK/UT4_TcpMessaging_classes.hpp"
#include "SDK/UT4_TcpMessaging_parameters.hpp"
#include "SDK/UT4_Serialization_structs.hpp"
#include "SDK/UT4_Serialization_classes.hpp"
#include "SDK/UT4_Serialization_parameters.hpp"
#include "SDK/UT4_UdpMessaging_structs.hpp"
#include "SDK/UT4_UdpMessaging_classes.hpp"
#include "SDK/UT4_UdpMessaging_parameters.hpp"
#include "SDK/UT4_BaseUTVoice_structs.hpp"
#include "SDK/UT4_BaseUTVoice_classes.hpp"
#include "SDK/UT4_BaseUTVoice_parameters.hpp"
#include "SDK/UT4_WmfMediaFactory_structs.hpp"
#include "SDK/UT4_WmfMediaFactory_classes.hpp"
#include "SDK/UT4_WmfMediaFactory_parameters.hpp"
#include "SDK/UT4_ThundercrashVoice_structs.hpp"
#include "SDK/UT4_ThundercrashVoice_classes.hpp"
#include "SDK/UT4_ThundercrashVoice_parameters.hpp"
#include "SDK/UT4_Malcolm_New_structs.hpp"
#include "SDK/UT4_Malcolm_New_classes.hpp"
#include "SDK/UT4_Malcolm_New_parameters.hpp"
#include "SDK/UT4_BlueprintContext_structs.hpp"
#include "SDK/UT4_BlueprintContext_classes.hpp"
#include "SDK/UT4_BlueprintContext_parameters.hpp"
#include "SDK/UT4_FacialAnimation_structs.hpp"
#include "SDK/UT4_FacialAnimation_classes.hpp"
#include "SDK/UT4_FacialAnimation_parameters.hpp"
#include "SDK/UT4_EngineMessages_structs.hpp"
#include "SDK/UT4_EngineMessages_classes.hpp"
#include "SDK/UT4_EngineMessages_parameters.hpp"
#include "SDK/UT4_Enforcer_AnimBP_structs.hpp"
#include "SDK/UT4_Enforcer_AnimBP_classes.hpp"
#include "SDK/UT4_Enforcer_AnimBP_parameters.hpp"
#include "SDK/UT4_MediaAssets_structs.hpp"
#include "SDK/UT4_MediaAssets_classes.hpp"
#include "SDK/UT4_MediaAssets_parameters.hpp"
#include "SDK/UT4_GibHumanBase_structs.hpp"
#include "SDK/UT4_GibHumanBase_classes.hpp"
#include "SDK/UT4_GibHumanBase_parameters.hpp"
#include "SDK/UT4_GibHumanArmR_structs.hpp"
#include "SDK/UT4_GibHumanArmR_classes.hpp"
#include "SDK/UT4_GibHumanArmR_parameters.hpp"
#include "SDK/UT4_BuildPatchServices_structs.hpp"
#include "SDK/UT4_BuildPatchServices_classes.hpp"
#include "SDK/UT4_BuildPatchServices_parameters.hpp"
#include "SDK/UT4_MoviePlayer_structs.hpp"
#include "SDK/UT4_MoviePlayer_classes.hpp"
#include "SDK/UT4_MoviePlayer_parameters.hpp"
#include "SDK/UT4_GameLiveStreaming_structs.hpp"
#include "SDK/UT4_GameLiveStreaming_classes.hpp"
#include "SDK/UT4_GameLiveStreaming_parameters.hpp"
#include "SDK/UT4_HeadMountedDisplay_structs.hpp"
#include "SDK/UT4_HeadMountedDisplay_classes.hpp"
#include "SDK/UT4_HeadMountedDisplay_parameters.hpp"
#include "SDK/UT4_DmgTypeBP_Environmental_structs.hpp"
#include "SDK/UT4_DmgTypeBP_Environmental_classes.hpp"
#include "SDK/UT4_DmgTypeBP_Environmental_parameters.hpp"
#include "SDK/UT4_GibHumanArmL_structs.hpp"
#include "SDK/UT4_GibHumanArmL_classes.hpp"
#include "SDK/UT4_GibHumanArmL_parameters.hpp"
#include "SDK/UT4_PhysXVehicles_structs.hpp"
#include "SDK/UT4_PhysXVehicles_classes.hpp"
#include "SDK/UT4_PhysXVehicles_parameters.hpp"
#include "SDK/UT4_Qos_structs.hpp"
#include "SDK/UT4_Qos_classes.hpp"
#include "SDK/UT4_Qos_parameters.hpp"
#include "SDK/UT4_Landscape_structs.hpp"
#include "SDK/UT4_Landscape_classes.hpp"
#include "SDK/UT4_Landscape_parameters.hpp"
#include "SDK/UT4_GibHumanTorso_structs.hpp"
#include "SDK/UT4_GibHumanTorso_classes.hpp"
#include "SDK/UT4_GibHumanTorso_parameters.hpp"
#include "SDK/UT4_GibHumanRibs_structs.hpp"
#include "SDK/UT4_GibHumanRibs_classes.hpp"
#include "SDK/UT4_GibHumanRibs_parameters.hpp"
#include "SDK/UT4_EngineSettings_structs.hpp"
#include "SDK/UT4_EngineSettings_classes.hpp"
#include "SDK/UT4_EngineSettings_parameters.hpp"
#include "SDK/UT4_GibHumanLegR_structs.hpp"
#include "SDK/UT4_GibHumanLegR_classes.hpp"
#include "SDK/UT4_GibHumanLegR_parameters.hpp"
#include "SDK/UT4_GibHumanLegL_structs.hpp"
#include "SDK/UT4_GibHumanLegL_classes.hpp"
#include "SDK/UT4_GibHumanLegL_parameters.hpp"
#include "SDK/UT4_GibHumanHead_structs.hpp"
#include "SDK/UT4_GibHumanHead_classes.hpp"
#include "SDK/UT4_GibHumanHead_parameters.hpp"
#include "SDK/UT4_MaterialShaderQualitySettings_structs.hpp"
#include "SDK/UT4_MaterialShaderQualitySettings_classes.hpp"
#include "SDK/UT4_MaterialShaderQualitySettings_parameters.hpp"

/*
# ========================================================================================= #
# Math
# ========================================================================================= #
*/
FVector inline VectorSubtract(FVector Vector1, FVector Vector2)
{
	FVector Vec;
	Vec.X = Vector1.X - Vector2.X;
	Vec.Y = Vector1.Y - Vector2.Y;
	Vec.Z = Vector1.Z - Vector2.Z;
	return Vec;
}
FVector inline VectorAdd(FVector Vector1, FVector Vector2)
{
	FVector Vec;
	Vec.X = Vector1.X + Vector2.X;
	Vec.Y = Vector1.Y + Vector2.Y;
	Vec.Z = Vector1.Z + Vector2.Z;
	return Vec;
}
FRotator inline RotatorSubtract(FRotator Vector1, FRotator Vector2)
{
	FRotator Vec;
	Vec.Pitch = Vector1.Pitch - Vector2.Pitch;
	Vec.Yaw = Vector1.Yaw - Vector2.Yaw;
	Vec.Roll = Vector1.Roll - Vector2.Roll;
	return Vec;
}
FRotator inline RotatorAdd(FRotator Vector1, FRotator Vector2)
{
	FRotator Vec;
	Vec.Pitch = Vector1.Pitch + Vector2.Pitch;
	Vec.Yaw = Vector1.Yaw + Vector2.Yaw;
	Vec.Roll = Vector1.Roll + Vector2.Roll;
	return Vec;
}
FRotator inline LimitRotation(UKismetMathLibrary* gMath, FRotator rStartRotation, FRotator rEndRotation)
{
	float nMaxRotation = 360.0f;

	FRotator rDeltaRotation;
	rDeltaRotation = gMath->STATIC_NormalizedDeltaRotator(rEndRotation, rStartRotation);

	// yaw
	if (rDeltaRotation.Yaw > nMaxRotation) { rDeltaRotation.Yaw = nMaxRotation; }
	else if (rDeltaRotation.Yaw < -nMaxRotation) { rDeltaRotation.Yaw = -nMaxRotation; }

	// pitch
	if (rDeltaRotation.Pitch > nMaxRotation) { rDeltaRotation.Pitch = nMaxRotation; }
	else if (rDeltaRotation.Pitch < -nMaxRotation) { rDeltaRotation.Pitch = -nMaxRotation; }

	// roll
	//if ( rDeltaRotation.Roll > nMaxRotation  ) { rDeltaRotation.Roll = nMaxRotation; }
	//else if ( rDeltaRotation.Roll < -nMaxRotation ) { rDeltaRotation.Roll = -nMaxRotation; }

	return RotatorAdd(rStartRotation, rDeltaRotation);
}

/*
# ========================================================================================= #
# Custom
# ========================================================================================= #
*/
class gUnrealInfo
{
public:
	UWorld* GWorld;
	UEngine* gEngine;
	AUTPlayerController* gPlayerController;
	UGameplayStatics* gGameplayStatics;
	UKismetMathLibrary* gMath;
	BOOLEAN Initialize;
	DWORD64 gProcessEvent;
	gUnrealInfo() {
		GWorld = 0;
		gEngine = 0;
		gPlayerController = 0;
		gMath = 0;
		Initialize = 0;
		gProcessEvent = 0;
	}
};

/*
# ========================================================================================= #
# Useless functions and placeholders
# ========================================================================================= #
*/